select b.AUTHOR_ID, AUTHOR_NAME, CATEGORY, sum(SALES * PRICE) as TOTAL_SALES
from BOOK b
join AUTHOR a on a.AUTHOR_ID = b.AUTHOR_ID
join BOOK_SALES bs on bs.BOOK_ID = b.BOOK_ID
where SALES_DATE like '2022-01-%'
group by AUTHOR_ID, CATEGORY
order by AUTHOR_ID, CATEGORY desc
